model_name_or_path: /path/to/models/Qwen2-1.5B
trust_remote_code: true

stage: sft
do_train: true
report_to: tensorboard
logging_dir: /path/to/runs/qwen1.5b_sciq_lora
finetuning_type: lora
lora_target:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
lora_rank: 16
flash_attn: fa2

dataset_dir: /path/to/datasets/SciQ
dataset: sciq
max_samples: null
template: qwen
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16

output_dir: /path/to/outputs/qwen1.5b_sciq_lora

logging_steps: 10
save_steps: 100
plot_loss: true

per_device_train_batch_size: 16
gradient_accumulation_steps: 2
learning_rate: 4.0e-5
num_train_epochs: 5
max_steps: 2400
max_grad_norm: 0.5
lr_scheduler_type: cosine
warmup_ratio: 0.1
weight_decay: 0.05

val_size: 0.1
per_device_eval_batch_size: 16
eval_strategy: steps
eval_steps: 100

gradient_checkpointing: true
optim: adamw_torch
